### ISSUE TITLE
Error trying to run iotop after install

### ISSUE THREAD

**Issue by Daxcor69** [Tomas-M/iotop#67]
I am trying to run iotop on a ubuntu 22.04.3 minimal install.  I think I am missing a dependency. I just have no way to figure out which one.  This does work on a regular install of ubuntu.

Any help would be appreciated. Thanks

Brad 

Traceback (most recent call last):
  File "/usr/sbin/iotop", line 10, in <module>
    from iotop.ui import main
  File "/usr/lib/python3/dist-packages/iotop/ui.py", line 46, in <module>
    from iotop.data import find_uids, TaskStatsNetlink, ProcessList, Stats
  File "/usr/lib/python3/dist-packages/iotop/data.py", line 51, in <module>
    vmstat_f = VmStat()
  File "/usr/lib/python3/dist-packages/iotop/vmstat.py", line 23, in __init__
    self.vmstat = self.read()
  File "/usr/lib/python3/dist-packages/iotop/vmstat.py", line 40, in read
    return pgpgin, pgpgout
UnboundLocalError: local variable 'pgpgin' referenced before assignment

**Comment by bbonev** [comment]
Seems like you are using `iotop-py`, the git repo is [here](https://repo.or.cz/w/iotop.git)

This repo is `iotop-c`, you can install on ubuntu by 

````sh
apt install iotop-c
````
